// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzs7CvCfE4eYnN4nuCxSNqzEkHJ0YCE70',
    appId: '1:390182579356:web:d83fadf757344eaa8a5159',
    messagingSenderId: '390182579356',
    projectId: 'claws-5a739',
    authDomain: 'claws-5a739.firebaseapp.com',
    storageBucket: 'claws-5a739.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAteoSuD-AbAlDbC3fM0CGToc8-ynu4hvA',
    appId: '1:390182579356:android:fbdbe3e5c346570f8a5159',
    messagingSenderId: '390182579356',
    projectId: 'claws-5a739',
    storageBucket: 'claws-5a739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXU6a646f5m0Rwou85uWBvaf3CQntlpmM',
    appId: '1:390182579356:ios:2edf4344a36cb9238a5159',
    messagingSenderId: '390182579356',
    projectId: 'claws-5a739',
    storageBucket: 'claws-5a739.appspot.com',
    iosBundleId: 'com.example.claws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXU6a646f5m0Rwou85uWBvaf3CQntlpmM',
    appId: '1:390182579356:ios:2edf4344a36cb9238a5159',
    messagingSenderId: '390182579356',
    projectId: 'claws-5a739',
    storageBucket: 'claws-5a739.appspot.com',
    iosBundleId: 'com.example.claws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzs7CvCfE4eYnN4nuCxSNqzEkHJ0YCE70',
    appId: '1:390182579356:web:36fe309570336cde8a5159',
    messagingSenderId: '390182579356',
    projectId: 'claws-5a739',
    authDomain: 'claws-5a739.firebaseapp.com',
    storageBucket: 'claws-5a739.appspot.com',
  );
}
